#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xlrd
Version  : 1.0.0
Release  : 1
URL      : https://pypi.python.org/packages/42/85/25caf967c2d496067489e0bb32df069a8361e1fd96a7e9f35408e56b3aab/xlrd-1.0.0.tar.gz
Source0  : https://pypi.python.org/packages/42/85/25caf967c2d496067489e0bb32df069a8361e1fd96a7e9f35408e56b3aab/xlrd-1.0.0.tar.gz
Summary  : Library for developers to extract data from Microsoft Excel (tm) spreadsheet files
Group    : Development/Tools
License  : BSD-4-Clause
Requires: xlrd-bin
Requires: xlrd-python
Requires: Sphinx
Requires: nose
Requires: six
Requires: tox
Requires: wheel
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
### Python package "xlrd"
**Purpose**: Provide a library for developers to use to extract data from Microsoft Excel (tm) spreadsheet files. It is not an end-user tool.

%package bin
Summary: bin components for the xlrd package.
Group: Binaries

%description bin
bin components for the xlrd package.


%package python
Summary: python components for the xlrd package.
Group: Default

%description python
python components for the xlrd package.


%prep
%setup -q -n xlrd-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1498668264
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1498668264
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/runxlrd.py

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
